// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK5VaLT4kqgetalf9LJoXKjRBd_Pu4BHw',
    appId: '1:96268264420:web:b5558d0e87273f1af3ddf1',
    messagingSenderId: '96268264420',
    projectId: 'schoolerp-5df03',
    authDomain: 'schoolerp-5df03.firebaseapp.com',
    storageBucket: 'schoolerp-5df03.firebasestorage.app',
    measurementId: 'G-J6JHYESS4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLEk3lJcv2v8ioETGWeFY-R-_Bvj4gTx4',
    appId: '1:96268264420:android:ae14c0db23efc909f3ddf1',
    messagingSenderId: '96268264420',
    projectId: 'schoolerp-5df03',
    storageBucket: 'schoolerp-5df03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTW3fL8TtzD-Ob-VOLnDu-WpFAS--QyVw',
    appId: '1:96268264420:ios:1a2ad0cbc0c607d2f3ddf1',
    messagingSenderId: '96268264420',
    projectId: 'schoolerp-5df03',
    storageBucket: 'schoolerp-5df03.firebasestorage.app',
    iosBundleId: 'com.example.schoolPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTW3fL8TtzD-Ob-VOLnDu-WpFAS--QyVw',
    appId: '1:96268264420:ios:1a2ad0cbc0c607d2f3ddf1',
    messagingSenderId: '96268264420',
    projectId: 'schoolerp-5df03',
    storageBucket: 'schoolerp-5df03.firebasestorage.app',
    iosBundleId: 'com.example.schoolPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK5VaLT4kqgetalf9LJoXKjRBd_Pu4BHw',
    appId: '1:96268264420:web:2744939ec8ac63a8f3ddf1',
    messagingSenderId: '96268264420',
    projectId: 'schoolerp-5df03',
    authDomain: 'schoolerp-5df03.firebaseapp.com',
    storageBucket: 'schoolerp-5df03.firebasestorage.app',
    measurementId: 'G-8RF0SFQ2P8',
  );
}
